AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Quick-sight

Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 30

Resources:
  TestDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: testData.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        TeamsApi:
          Type: Api
          Properties:
            Path: /testData
            Method: post

Outputs:
  Url:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/test/"

